name: maven test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '19' ]
    name: 'Java ${{ matrix.java }} maven test'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v3'
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: 'actions/setup-java@v3'
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'adopt'
      - name: 'Build & test with Maven'
        run: 'mvn test'
      - name: 'upload code coverage'
        if: ${{ matrix.java == '11' }}
        uses: 'codecov/codecov-action@v4'
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          files: 'target/site/jacoco/jacoco.xml'
          name: 'codecov-umbrella'
          flags: unittests # optional
          verbose: true # optional (default = false)
